spring:
  application:
    name: game-service
  profiles:
    active: dev

  #for avoiding Open-In-View warnings:
  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

game:
  timer:
    betting-time: 120
    decision-time: 25

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never




clients:
  services:
    user:
      base-url: ${USER_SERVICE_BASE_URL}
    money:
      base-url: ${MONEY_SERVICE_BASE_URL}

jwt:
  secrets:
    user: ${JWT_USER_SECRET}         # user JWT
    internal: ${JWT_INTERNAL_SECRET} # internal JWT (interservice)

security:
  user:
    issuer: ${JWT_USER_ISSUER}
  internal:
    issuer: ${JWT_INTERNAL_ISSUER}
    expected-audience: game-service
    allowed-subjects: user-service,money-service

