spring:
  application:
    name: game-service
  profiles:
    active: dev  #default profile


  #for avoiding Open-In-View warnings:
  jpa:
    open-in-view: false


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

#  cache:
#    type=none:#  profiles:

game:
  timer:
    betting-time: 120
    decision-time: 25

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never


jwt:
  game-secret: ${JWT_GAME_SECRET}
  system-secret: ${JWT_SYSTEM_SECRET}

