spring:
  application:
    name: game-service
  profiles:
    active: dev  #default profile

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

#  cache:
#    type=none:#  profiles:

game:
  timer:
    betting-time: 120
    decision-time: 25

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  game-secret: ${JWT_GAME_SECRET}
  system-secret: ${JWT_SYSTEM_SECRET}

