package com.evofun.gameservice.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHORIZATION,
    GAME_RULE_VIOLATION,
    ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    SYSTEM_ERROR,
    INVALID_REQUEST_FORMAT,
    FORBIDDEN,
    SERVICE_UNAVAILABLE, UNKNOWN_ERROR
}